sudar/bulk-delete

bulk-delete.php, include/class-bulk-delete-by-days.php, include/class-bulk-delete-pages.php, include/class-bulk-delete-posts.php, include/class-bulk-delete-users.php, include/class-bulk-delete-util.php, include/class-cron-list-table.php, include/class-license-list-table.php, include/libraries/browser.php
@sudar requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/sudar/bulk-delete/
=> Scrutinizer Auto-Fixes

bulk-delete.php, include/base/class-bd-base-page.php, include/meta/class-bulk-delete-meta.php, include/misc/class-bulk-delete-misc.php, include/settings/class-bd-settings-page.php, include/system-info/class-bd-system-info-page.php, include/ui/form.php
https://github.com/sudar/bulk-delete/issues/132
=> Remove iFrames sidebar on all Bulk Delete admin pages

include/meta/class-bulk-delete-post-meta.php
=> 174 feature/show pro content

assets/js/src/bulk-delete.js, bulk-delete.php, include/posts/class-bulk-delete-posts.php
=> Plugin page crashes if there are huge number of taxonomies

assets/js/src/bulk-delete.js, bulk-delete.php
=> Update ajax call prefix

tests/wp-unit/tests/include/posts/Bulk_Delete_Posts_By_Post_TagTest.php
=> 173 fix/add tests for delete posts by tag

tests/wp-unit/tests/include/users/Bulk_Delete_Users_By_User_MetaTest.php
=> 196 fix test for deleting users by meta

include/Core/Pages/Modules/DeletePagesByStatusModule.php, include/deprecated/deprecated.php, tests/wp-unit/include/Core/Pages/Modules/DeletePagesByStatusModuleInOldFormatTest.php, tests/wp-unit/include/Core/Pages/Modules/DeletePagesByStatusModuleTest.php, tests/wp-unit/include/Core/Posts/Modules/DeletePostsByStatusModuleTest.php
=> Delete Pages by Post status - Add support for custom post status

include/Core/Metas/Modules/DeleteUserMetaModule.php
=> Fix undefiened error

include/license/class-bd-license-handler.php
=> Show "license invalid" message only to admins

include/helpers/common.php, include/system-info/class-bd-system-info-page.php
=> Display details about all scheduled jobs in system info

include/helpers/common.php
=> Unused variable

assets/js/src/delete-posts-by-sticky-post.js, include/Core/Base/BaseModule.php, include/Core/BulkDelete.php, include/Core/Posts/Modules/DeletePostsByStickyPostModule.php, include/Core/Posts/PostsModule.php, include/deprecated/class-bulk-delete-posts.php, include/ui/form.php
=> Add delete by sticky post module

assets/js/src/delete-posts-by-sticky-post.js
=> Fix js grunt issue

include/Core/Cron/CronListPage.php, include/Core/Cron/CronListTable.php
=> Add run now option in schedule job

include/Core/Posts/PostsModule.php
=> Check if sticky post is an array before using it

assets/js/src/delete-posts-by-post-type.js, assets/js/src/select2.js, include/Core/Base/Mixin/Renderer.php
The select2 bug prevents the post type select2 from working. It is
explained in this codepen https://codepen.io/anon/pen/MXdorM
Fix #344
=> Refactor how post type select2 is handled to circumvent select2 bug

include/Core/Posts/Modules/DeletePostsByTagModule.php, include/helpers/common.php
=> Set default values while trying to get values from request

tests/wp-unit/include/Core/Metas/Modules/DeletePostMetaModuleTest.php
=> Standardize test method names

tests/wp-unit/include/Core/Users/Modules/DeleteUsersByUserMetaModuleTest.php
=> no_posts_post_types is array now Fix #380

tests/wp-unit/include/Core/Posts/Modules/DeletePostsByTaxonomyModuleTest.php
=> Delete Posts by Custom Taxonomies Test Case

tests/wp-unit/include/Core/Posts/Modules/DeletePostsByTaxonomyModuleTest.php
Split data providers and add missing tests in DeletePostsByTaxonomy module
Fix #345
=> PR: #345 [Delete Posts By Taxonomy] Missing Test cases

composer.lock, tests/wp-unit/include/Core/Posts/Modules/DeletePostsByStickyPostModuleTest.php
Add tests for sticky posts module.
Fix #354
=> PR: Delete Sticky posts: Add Tests #354 

include/Core/Metas/Modules/DeleteCommentMetaModule.php
Swap operator and datatype dropdowns in Delete Comment Meta Module.
Fix #460
=> PR: Delete Comment Meta Operators restriction #460

include/Core/Metas/MetasModule.php, include/Core/Metas/Modules/DeleteCommentMetaModule.php
Rename label in delete comment meta module
Fix #491
=> PR: Delete Comment Meta - Rename label #491

include/Core/Users/Modules/DeleteUsersByUserMetaModule.php
Allows empty value in Meta Value text box
Fix #528
=> PR: DeleteUsersByMeta - Need to allow empty values in the value textbox #528

assets/js/src/bulk-delete.js, assets/js/src/delete-posts-by-post-type.js, include/Core/Posts/PostsModule.php
Adds Javascript validation for delete posts by status, category, tag and post type.
Fix #517
=> PR: Confirmation dialog appears when nothing is selected #517

include/Core/Terms/Modules/DeleteTermsByNameModule.php, tests/wp-unit/include/Core/Terms/Modules/DeleteTermsByNameModuleTest.php
Adds blank validation for term name  and adds blank value dataset to test
Fix #532
=> PR: DeleteTermsByName: All Terms are deleted when nothing is entered for term name #532

assets/js/src/delete-posts-by-sticky-post.js, include/Core/Base/Mixin/Renderer.php
Sticky Posts Module: Uncheck and disable other checkboxes when all is choosen
=> PR: Delete Sticky Posts - When 'All' is choosen, uncheck and disable all the other checkboxes #544

assets/css/src/delete-post-by-url.css
=> Fix alignment issue in Delete Posts by URL module

include/Core/Posts/PostsModule.php, include/Core/Users/UsersModule.php
Adds Filters for adding exclude post ids and user ids.
=> PR: Introduce a filter to exclude certain post ids and user ids #558

assets/js/src/bulk-delete.js
Fix https://github.com/sudar/bulk-delete/issues/555
=> Fix jQuery element selector by adding the missing `]`

include/Core/Base/Mixin/Renderer.php
Adds place holder text for Post Type dropdown.
Fix #571
=> PR: Delete Posts by Post Type - Show a place holder in the post type selection #571

include/Core/Base/Mixin/Renderer.php, include/Core/Metas/Modules/DeleteUserMetaModule.php, include/misc/class-bulk-delete-jetpack-contact-form-messages.php, include/ui/form.php
Add autocomplete attribute.
Fix #588
=> PR: Turn off Browser AutoComplete #588

include/Core/Base/Mixin/Renderer.php
Change camelcase labels to lowercase
Fix #591
=> PR: Change camel case labels to lower case in string comparison operators dropdown #591

include/Core/Metas/Modules/DeleteUserMetaModule.php
Use helper functions in renderer instead of repeating it in module.
Fix #593
=> PR: UserMetaModule: Use existing functions for rendering limit and cron settings #593

tests/wp-unit/include/Core/Users/UsersModuleTest.php
Add tests for all filters in UserModule base class.
Fix #540
=> PR: DeleteUsersModule Tests #540

include/Core/Base/Mixin/Renderer.php
=> PR: Fix typo in render_post_type_with_status #607

include/Core/Addon/UpsellModule.php, include/Core/Base/Mixin/Renderer.php
Open buy now links in new tab
Fix #599
=> PR: Open buy now links in a new tab #599

assets/js/src/validation-helpers.js, include/Core/Base/Mixin/Renderer.php
Change submit button text based on cron selection.
Fix #604
=> PR: If the user is scheduling deletion then change the submit button text #604

include/Core/Base/Mixin/Renderer.php
List built in custom taxonomies separately.
Fix #603
=> PR: List built-in taxonomies and custom taxonomies as seperate groups in taxonomy list dropdown #603

assets/js/src/bulk-delete.js, assets/js/src/validation-helpers.js, include/Core/Base/BaseDeletePage.php, include/Core/Base/BaseModule.php, include/Core/Base/Mixin/Renderer.php, include/Core/Posts/Modules/DeletePostsByPostTypeModule.php, include/Core/Posts/Modules/DeletePostsByStatusModule.php
Display different confirmation message based on `Delete now/Schedule` is selected.
Requires https://github.com/sudar/bulk-delete/pull/610
Fix #595
=> Show a different confirmation message if the user is scheduling deletion instead of deleting right away #595

assets/js/src/validation-helpers.js
Add validate class to jQuery selector.
Fix #619
=> PR:  Refactor Javascript functions #619 Open
